### PR TITLE
Splash Screen Added

### PR DESCRIPTION
**Pull request by Manas-33**
Please check, I have added the required functionality.
splashScreen

### CODE REVIEW

**Review by aastha9199 — CHANGES_REQUESTED** [review]
1. Use Media Query instead of static values
2. Change time duration to 3 seconds

**Comment by Manas-33** [comment]
I have made the changes @aastha9199

**Comment by Manas-33** [comment]
Can you please review and merge this @IshanRakte?

**Comment by sahil-patil17** [comment]
Thanks for contributing!

**Comment by aastha9199** [comment]
Done. Thank you!

**Pull request merged**
